import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import * as Localization from 'expo-localization';

const resources = {
  fr: {
    translation: {
      // ... (Gardez tout le contenu précédent des Lots 1-5) ...
      // AJOUTEZ JUSTE CECI DANS LA SECTION 'profile' :
      // Je remets tout le fichier pour éviter les erreurs de copier-coller partiel.
      landing: { title: "TRANSFORMEZ VOTRE CORPS\nAVEC L'INTELLIGENCE ARTIFICIELLE", subtitle: "Coach Sportif • Nutritionniste • Bio-Tracker", start_btn: "COMMENCER L'AVENTURE", login_btn: "J'ai déjà un compte", legal: "En continuant, vous acceptez nos CGU et confirmez que Nexus ne remplace pas un médecin." },
      auth: { welcome: "BIENVENUE", subtitle: "Connectez-vous au système", email_placeholder: "Adresse Email", password_placeholder: "Mot de passe", login_action: "SE CONNECTER", signup_action: "S'INSCRIRE", or: "OU", google: "CONTINUER AVEC GOOGLE", switch_to_signup: "Pas encore de compte ? Créer un profil", switch_to_login: "Déjà membre ? Se connecter", error_title: "Authentification échouée" },
      onboarding: { step1: "TON OBJECTIF ULTIME ?", step2: "TON NIVEAU ACTUEL ?", step3: "TON MATÉRIEL ?", next: "SUIVANT", finish: "TERMINER & GÉNÉRER", goals: { lose_weight: "Perte de Poids", muscle: "Prise de Masse", endurance: "Endurance & Cardio", strength: "Force Athlétique" }, levels: { beginner: "Débutant (0-1 an)", intermediate: "Intermédiaire (1-3 ans)", advanced: "Avancé (+3 ans)" }, equip: { gym: "Salle de Sport Complète", home: "Maison (Haltères/Elastiques)", bodyweight: "Poids du corps (Street)" } },
      tabs: { cockpit: "COCKPIT", sport: "SPORT", neural: "NEURAL", fuel: "FUEL", modules: "MODULES" },
      dashboard: { greeting: "BONJOUR", stats_nutri: "NUTRITION", stats_work: "ENTRAÎNEMENT", unit_sessions: "SÉANCES (7J)", unit_kcal: "KCAL / JOUR", section_active: "EN COURS", section_explore: "EXPLORER", active_badge: "PLAN ACTIF", no_plan_title: "Aucun programme", no_plan_desc: "Créez votre plan personnalisé avec l'IA.", card_focus: "Focus", card_sess: "séances", mod_nutri: "Nutrition", mod_nutri_sub: "Plan actif", mod_gen: "Générer", mod_lib: "Bibliothèque", mod_lib_sub: "+200 mouvements", mod_hist: "Historique", mod_hist_sub: "Vos progrès", mod_coach: "Neural Coach", mod_coach_sub: "Discussion IA" },
      
      // --- MODIFICATION ICI : AJOUT DE 'language' ---
      profile: { 
        language: "Langue", // <--- NOUVEAU
        title: "PROFIL NEXUS", default_name: "INITIÉ NEXUS", section_info: "INFORMATIONS PERSONNELLES", label_name: "Nom complet", ph_name: "Votre nom complet", label_age: "ÂGE", ph_age: "Vôtre âge", label_weight: "POIDS (KG)", label_height: "TAILLE (CM)", label_goal: "OBJECTIF", ph_goal: "Perte de poids...", label_level: "NIVEAU D'EXPÉRIENCE", label_equip: "MATÉRIEL DISPONIBLE", label_freq: "SÉANCES / SEM", section_physique: "PHYSIQUE & SANTÉ", section_config: "CONFIGURATION SPORTIVE", section_stats: "STATISTIQUES", stat_streak: "Jours Streak", stat_points: "Points", stat_level: "Niveau", stat_weight: "Kg Actuel", section_sub: "ABONNEMENT", badge_active: "ACTIF", sub_renewal: "Renouvellement :", sub_auto: "Renouvellement automatique", member_elite: "MEMBRE ELITE", member_standard: "MEMBRE STANDARD", sub_free: "GRATUIT", sub_desc_free: "Accès limité.", sub_desc_premium: "Accès illimité IA", sub_action: "Passer à la vitesse supérieure", sub_manage: "Gérer mon abonnement", btn_save: "ENREGISTRER LES MODIFICATIONS", btn_saving: "SAUVEGARDE...", section_settings: "PARAMÈTRES", theme: "Mode Sombre / Clair", support: "Support & Aide", legal: "Mentions Légales & CGU", logout: "Déconnexion", section_danger: "ZONE DE DANGER", deactivate: "Désactiver le compte", delete: "Supprimer mon compte", alerts: { welcome: "Bienvenue", welcome_msg: "Premium débloqué !", sub_downgrade: "Mode Gratuit", error: "Erreur", error_plan: "Impossible de changer.", confirm_logout: "Déconnexion ?", success: "Succès", saved: "Profil sauvegardé" }, footer: { version: "NEXUS AI FIT v1.0", system: "SYSTÈME DE GESTION BIOLOGIQUE", copyright: "© 2025 NEXUS INC." } 
      },
      
      coach: { intro: "Système NEXUS activé. Je suis prêt à optimiser vos performances. Quelle est la mission aujourd'hui ?", locked_title: "ACCÈS CLASSÉ DÉFENSE", locked_desc: "Le Neural Coach analyse vos performances en temps réel. Cette technologie est réservée aux membres Elite.", btn_unlock: "ACTIVER L'ACCÈS ELITE", placeholder: "Posez une question...", error_network: "Erreur de communication avec le QG.", error_server: "Désolé, mes systèmes neuronaux ne répondent pas." },
      library: { title: "BIBLIOTHÈQUE NEXUS", available: "MOUVEMENTS DISPONIBLES", search_ph: "Rechercher un exercice...", filters: { all: "Tous", chest: "Pectoraux", back: "Dos", legs: "Jambes", shoulders: "Épaules", arms: "Bras", abs: "Abdominaux", cardio: "Cardio" }, protocol: "PROTOCOLE D'EXÉCUTION :", btn_video: "VOIR DÉMO", btn_add: "AJOUTER", empty_search: "Aucun exercice trouvé pour" },
      history: { title: "HISTORIQUE SÉANCES", stats_total: "SÉANCES TOTALES", stats_valid: "EXERCICES VALIDÉS", timeline: "TIMELINE", session_active: "Séance Active", session_rest: "Jour de Repos ?", completed_ex: "exercices complétés", empty: "Aucune séance enregistrée." },
      nutrition: { title: "FUEL", subtitle: "Nutrition", consumed: "CONSOMMÉ", target: "CIBLE", ia_title: "DIÉTÉTICIEN IA", ia_desc: "Générez une semaine de repas complète, adaptée à votre métabolisme et vos goûts.", pref_label: "PRÉFÉRENCES", pref_ph: "Ex: Végétarien, Budget étudiant, Sans gluten...", btn_generate: "GÉNÉRER LE PLAN", btn_regen: "RÉGÉNÉRER LE PLAN", alert_title: "Nouveau Menu Prêt", alert_msg: "Votre plan a été généré et calibré.", alert_error: "Impossible de générer le plan.", alert_zone: "Hors Zone", alert_zone_msg: "Concentrez-vous sur le plan d'aujourd'hui." },
      systems: { title: "SYSTÈMES", subtitle: "Centre de Commande", search_ph: "Rechercher un protocole...", locked_alert: "MODULE PREMIUM", locked_msg: "Passez à la version Elite pour débloquer", btn_unlock: "DÉBLOQUER", soon_title: "Bientôt", soon_msg: "Module en cours de développement.", categories: { bio: "BIO-TRACKING", perf: "PERFORMANCE", nutri: "NUTRITION", recup: "RÉCUPÉRATION & BIO-HACKING" }, modules: { body_fat: "Masse Grasse", water: "Hydratation", tdee: "Métabolisme", bmi: "Analyse IMC", sleep: "Analyse Sommeil", stress: "Niveau Stress", heart: "Cardio Fréq.", body: "Body Battery", '1rm': "Calculateur 1RM", timer: "Chrono Tactique", workout_log: "Historique Séances", reflex: "Test Réflexes", vision: "Vision Focus", posture: "Analyse Posture", macros: "Calculateur Macros", shopping: "Liste Courses", supps: "Stack Suppléments", fasting: "Jeûne Intermit.", meal_prep: "Chef Meal Prep", breath: "Respiration", stretching: "Routine Souplesse", mood: "État Neural", meditation: "Méditation Zen", journaling: "Journal de Bord", cold: "Suivi Froid", nootropics: "Guide Nootropiques", env: "Scanner Environ.", hrv: "Optimisation VFC", discharge: "Neuro-Discharge" } },
      subscription: { badge: "NEXUS ELITE", status_badge: "STATUT : MEMBRE ELITE", title_free: "DÉPASSEZ VOS LIMITES", title_pro: "VOTRE ABONNEMENT", subtitle: "Débloquez l'intelligence artificielle complète pour une transformation physique accélérée.", active_title: "Abonnement Actif", active_renewal: "Prochain renouvellement : 01/01/2026", manage_btn: "GÉRER / ANNULER", manage_info: "Vous allez être redirigé vers les réglages de votre Store pour gérer l'abonnement.", features: { coach: "Coach IA Illimité (Chat)", plans: "Plans Nutrition & Sport 100% Perso", bio: "Analyse Biométrique (VFC, Sommeil)", recipes: "Recettes & Listes de Courses", support: "Support Prioritaire" }, price_month: "/ mois", btn_start: "COMMENCER L'ESSAI", btn_restore: "Restaurer les achats", legal_terms: "Conditions Générales", legal_privacy: "Confidentialité", alert_pay_title: "Paiement (Simulation)", alert_pay_msg: "En production, ceci ouvrira Apple Pay / Google Pay via RevenueCat.", alert_restore: "Restauration", alert_restore_msg: "Recherche d'abonnements existants..." },
      workout_tracker: { title: "WORKOUT TRACKER", available_moves: "MOUVEMENTS DISPONIBLES", ia_title: "GÉNÉRATEUR DE PROGRAMME", ia_desc: "L'IA va créer une semaine d'entraînement adaptée à votre matériel et votre niveau.", label_focus: "FOCUS PARTICULIER (Optionnel)", ph_focus: "Ex: Pecs, Fessiers, Cardio...", btn_generate: "GÉNÉRER LE PROGRAMME", plan_active: "PLAN ACTIF", btn_finish: "TERMINER LA SÉANCE", btn_regen: "GÉNÉRER UN NOUVEAU PROGRAMME", alert_ready_title: "Programme Prêt", alert_ready_msg: "Votre semaine d'entraînement a été générée !", alert_empty_title: "Séance vide", alert_empty_msg: "Cochez au moins un exercice.", alert_saved_title: "Séance Enregistrée ! 🚀", alert_saved_msg: "Bravo, votre historique a été mis à jour.", btn_history: "Voir l'historique", week_sessions: "SÉANCES / SEMAINE", day_session: "SÉANCE", exos_count: "EXOS", btn_demo: "DÉMO VIDÉO", protocol: "PROTOCOLE D'EXÉCUTION :" },
      shopping: { title: "LISTE DE COURSES", add_ph: "Ajouter un article...", empty: "Votre liste est vide.", empty_sub: "Ajoutez des articles ou générez un plan nutrition." },
      timer: { title: "CHRONO TACTIQUE", mode_rest: "REPOS", mode_tabata: "TABATA", start: "DÉMARRER", stop: "ARRÊTER", reset: "RESET", rounds: "ROUNDS", work: "TRAVAIL", rest: "REPOS" }
    }
  },
  en: {
    translation: {
      // ... LOT 1 ...
      landing: { title: "TRANSFORM YOUR BODY\nWITH AI", subtitle: "Coach • Nutritionist • Bio-Tracker", start_btn: "START JOURNEY", login_btn: "I have an account", legal: "By continuing, you accept TOS." },
      auth: { welcome: "WELCOME", subtitle: "Log in to system", email_placeholder: "Email", password_placeholder: "Password", login_action: "LOG IN", signup_action: "SIGN UP", or: "OR", google: "CONTINUE WITH GOOGLE", switch_to_signup: "No account? Create one", switch_to_login: "Member? Log in", error_title: "Auth failed" },
      onboarding: { step1: "ULTIMATE GOAL?", step2: "CURRENT LEVEL?", step3: "EQUIPMENT?", next: "NEXT", finish: "FINISH", goals: { lose_weight: "Weight Loss", muscle: "Muscle Gain", endurance: "Endurance", strength: "Power" }, levels: { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" }, equip: { gym: "Gym", home: "Home", bodyweight: "Bodyweight" } },
      
      // ... LOT 2 (MODIF: 'language') ...
      tabs: { cockpit: "COCKPIT", sport: "SPORT", neural: "NEURAL", fuel: "FUEL", modules: "MODULES" },
      dashboard: { greeting: "HELLO", stats_nutri: "NUTRITION", stats_work: "WORKOUT", unit_sessions: "SESSIONS (7D)", unit_kcal: "KCAL / DAY", section_active: "ACTIVE", section_explore: "EXPLORE", active_badge: "ACTIVE PLAN", no_plan_title: "No plan", no_plan_desc: "Create your plan with AI.", card_focus: "Focus", card_sess: "sessions", mod_nutri: "Nutrition", mod_nutri_sub: "Active plan", mod_gen: "Generate", mod_lib: "Library", mod_lib_sub: "+200 exercises", mod_hist: "History", mod_hist_sub: "Progress", mod_coach: "Neural Coach", mod_coach_sub: "AI Chat" },
      profile: { 
        language: "Language", // <--- NEW
        title: "PROFILE", default_name: "INITIATE", section_info: "PERSONAL INFO", label_name: "Full Name", ph_name: "Name", label_age: "AGE", ph_age: "Age", label_weight: "WEIGHT (KG)", label_height: "HEIGHT (CM)", label_goal: "GOAL", ph_goal: "Goal...", label_level: "LEVEL", ph_level: "Level...", section_config: "SPORT CONFIG", label_exp: "EXPERIENCE", label_equip: "EQUIPMENT", label_freq: "SESSIONS/WEEK", section_physique: "BODY & HEALTH", section_stats: "STATS", stat_streak: "Streak", stat_points: "Points", stat_level: "Level", stat_weight: "Current Kg", section_sub: "SUBSCRIPTION", badge_active: "ACTIVE", sub_renewal: "Renewal:", sub_auto: "Auto-renewal", member_elite: "ELITE MEMBER", member_standard: "STANDARD MEMBER", sub_free: "FREE", sub_desc_free: "Limited access.", sub_desc_premium: "Unlimited access", sub_action: "Upgrade", sub_manage: "Manage", btn_save: "SAVE", btn_saving: "SAVING...", section_settings: "SETTINGS", theme: "Dark/Light Mode", support: "Support", legal: "Legal", logout: "Logout", section_danger: "DANGER ZONE", deactivate: "Deactivate", delete: "Delete", alerts: { welcome: "Welcome", welcome_msg: "Premium unlocked!", sub_downgrade: "Free mode", error: "Error", error_plan: "Plan error", confirm_logout: "Logout?", success: "Success", saved: "Saved" }, footer: { version: "v1.0", system: "BIO MANAGEMENT SYSTEM", copyright: "© 2025 NEXUS" } 
      },
      // ... LOT 3, 4, 5 (Identique à FR traduit) ...
      coach: { intro: "NEXUS System Online. Ready to optimize performance. What is your mission?", locked_title: "RESTRICTED ACCESS", locked_desc: "Neural Coach reserved for Elite members.", btn_unlock: "ACTIVATE ELITE ACCESS", placeholder: "Ask a question...", error_network: "Network error.", error_server: "Systems not responding." },
      library: { title: "NEXUS LIBRARY", available: "MOVEMENTS AVAILABLE", search_ph: "Search exercise...", filters: { all: "All", chest: "Chest", back: "Back", legs: "Legs", shoulders: "Shoulders", arms: "Arms", abs: "Abs", cardio: "Cardio" }, protocol: "EXECUTION PROTOCOL:", btn_video: "WATCH DEMO", btn_add: "ADD", empty_search: "No exercise found for" },
      history: { title: "WORKOUT LOGS", stats_total: "TOTAL SESSIONS", stats_valid: "VALIDATED EXERCISES", timeline: "TIMELINE", session_active: "Active Session", session_rest: "Rest Day?", completed_ex: "exercises completed", empty: "No session recorded." },
      nutrition: { title: "FUEL", subtitle: "Nutrition", consumed: "CONSUMED", target: "TARGET", ia_title: "DIETICIAN AI", ia_desc: "Generate a full weekly meal plan.", pref_label: "PREFERENCES", pref_ph: "Ex: Vegetarian, Low budget...", btn_generate: "GENERATE PLAN", btn_regen: "REGENERATE PLAN", alert_title: "Menu Ready", alert_msg: "Plan generated.", alert_error: "Generation failed.", alert_zone: "Wrong Zone", alert_zone_msg: "Focus on today." },
      systems: { title: "SYSTEMS", subtitle: "Command Center", search_ph: "Search protocol...", locked_alert: "PREMIUM MODULE", locked_msg: "Upgrade to unlock", btn_unlock: "UNLOCK", soon_title: "Soon", soon_msg: "Under development.", categories: { bio: "BIO-TRACKING", perf: "PERFORMANCE", nutri: "NUTRITION", recup: "RECOVERY" }, modules: { body_fat: "Body Fat", water: "Hydration", tdee: "Metabolism", bmi: "BMI", sleep: "Sleep", stress: "Stress", heart: "Heart Rate", body: "Body Battery", '1rm': "1RM Calc", timer: "Timer", workout_log: "History", reflex: "Reflex", vision: "Vision", posture: "Posture", macros: "Macros", shopping: "Shopping", supps: "Supplements", fasting: "Fasting", meal_prep: "Meal Prep", breath: "Breathing", stretching: "Stretching", mood: "Mood", meditation: "Meditation", journaling: "Journaling", cold: "Cold Exp", nootropics: "Nootropics", env: "Environment", hrv: "HRV", discharge: "Discharge" } },
      subscription: { badge: "NEXUS ELITE", status_badge: "STATUS: ELITE", title_free: "BREAK LIMITS", title_pro: "YOUR SUBSCRIPTION", subtitle: "Unlock full AI.", active_title: "Active", active_renewal: "Renews: 01/01/2026", manage_btn: "MANAGE / CANCEL", manage_info: "Redirecting to Store.", features: { coach: "Unlimited Coach", plans: "Custom Plans", bio: "Bio-Metrics", recipes: "Recipes", support: "Support" }, price_month: "/ month", btn_start: "START TRIAL", btn_restore: "Restore", legal_terms: "Terms", legal_privacy: "Privacy", alert_pay_title: "Payment", alert_pay_msg: "Production uses RevenueCat.", alert_restore: "Restore", alert_restore_msg: "Searching..." },
      workout_tracker: { title: "WORKOUT TRACKER", available_moves: "MOVEMENTS AVAILABLE", ia_title: "PROGRAM GENERATOR", ia_desc: "AI will create a weekly plan based on your equipment and level.", label_focus: "PARTICULAR FOCUS (Optional)", ph_focus: "Ex: Chest, Glutes, Cardio...", btn_generate: "GENERATE PROGRAM", plan_active: "ACTIVE PLAN", btn_finish: "FINISH SESSION", btn_regen: "GENERATE NEW PROGRAM", alert_ready_title: "Program Ready", alert_ready_msg: "Your workout week is ready!", alert_empty_title: "Empty Session", alert_empty_msg: "Check at least one exercise.", alert_saved_title: "Session Saved! 🚀", alert_saved_msg: "Great job, history updated.", btn_history: "View History", week_sessions: "SESSIONS / WEEK", day_session: "SESSION", exos_count: "EXERCISES", btn_demo: "VIDEO DEMO", protocol: "EXECUTION PROTOCOL:" },
      shopping: { title: "SHOPPING LIST", add_ph: "Add item...", empty: "Your list is empty.", empty_sub: "Add items or generate a nutrition plan." },
      timer: { title: "TACTICAL TIMER", mode_rest: "REST", mode_tabata: "TABATA", start: "START", stop: "STOP", reset: "RESET", rounds: "ROUNDS", work: "WORK", rest: "REST" }
    }
  },
  ar: {
    translation: {
      // ... Copiez les traductions AR des Lots 1-5 ...
      landing: { title: "حول جسمك بالذكاء الاصطناعي", subtitle: "مدرب • تغذية • تتبع", start_btn: "ابدأ", login_btn: "دخول", legal: "بالمتابعة توافق على الشروط." },
      auth: { welcome: "مرحباً", subtitle: "تسجيل الدخول", email_placeholder: "البريد", password_placeholder: "كلمة المرور", login_action: "دخول", signup_action: "تسجيل", or: "أو", google: "جوجل", switch_to_signup: "حساب جديد", switch_to_login: "دخول", error_title: "خطأ" },
      onboarding: { step1: "الهدف؟", step2: "المستوى؟", step3: "المعدات؟", next: "التالي", finish: "إنهاء", goals: { lose_weight: "وزن", muscle: "عضلات", endurance: "تحمل", strength: "قوة" }, levels: { beginner: "مبتدئ", intermediate: "متوسط", advanced: "متقدم" }, equip: { gym: "جيم", home: "منزل", bodyweight: "وزن جسم" } },
      tabs: { cockpit: "الرئيسية", sport: "رياضة", neural: "عصبي", fuel: "وقود", modules: "وحدات" },
      dashboard: { greeting: "مرحباً", stats_nutri: "تغذية", stats_work: "تدريب", unit_sessions: "جلسات", unit_kcal: "سعرة", section_active: "جاري", section_explore: "استكشاف", active_badge: "نشط", no_plan_title: "لا توجد خطة", no_plan_desc: "أنشئ خطة.", card_focus: "تركيز", card_sess: "جلسات", mod_nutri: "تغذية", mod_nutri_sub: "نشط", mod_gen: "توليد", mod_lib: "مكتبة", mod_lib_sub: "+200", mod_hist: "سجل", mod_hist_sub: "تقدم", mod_coach: "مدرب", mod_coach_sub: "محادثة" },
      profile: { 
        language: "اللغة", // <--- NOUVEAU AR
        title: "ملفي", default_name: "عضو", section_info: "معلومات", label_name: "الاسم", ph_name: "اسمك", label_age: "العمر", ph_age: "عمرك", label_weight: "الوزن", label_height: "الطول", label_goal: "الهدف", ph_goal: "هدف...", label_level: "النشاط", ph_level: "مستوى...", section_config: "إعدادات", label_exp: "خبرة", label_equip: "معدات", label_freq: "جلسات", section_physique: "جسم", section_stats: "إحصاءات", stat_streak: "أيام", stat_points: "نقاط", stat_level: "مستوى", stat_weight: "وزن", section_sub: "اشتراك", badge_active: "نشط", sub_renewal: "تجديد", sub_auto: "تلقائي", member_elite: "نخبة", member_standard: "عادي", sub_free: "مجاني", sub_desc_free: "محدود", sub_desc_premium: "غير محدود", sub_action: "ترقية", sub_manage: "إدارة", btn_save: "حفظ", btn_saving: "جاري...", section_settings: "إعدادات", theme: "سمة", support: "دعم", legal: "قانوني", logout: "خروج", section_danger: "خطر", deactivate: "تعطيل", delete: "حذف", alerts: { welcome: "مرحباً", welcome_msg: "تم الفتح", sub_downgrade: "مجاني", error: "خطأ", error_plan: "فشل", confirm_logout: "خروج؟", success: "نجاح", saved: "حفظ" }, footer: { version: "v1.0", system: "نظام", copyright: "حقوق" } 
      },
      coach: { intro: "نظام نيكسس نشط. جاهز لتحسين الأداء. ما هي المهمة؟", locked_title: "وصول مقيد", locked_desc: "التحليل العصبي للمحترفين فقط.", btn_unlock: "تفعيل النخبة", placeholder: "اطرح سؤالاً...", error_network: "خطأ في الاتصال.", error_server: "الأنظمة لا تستجيب." },
      library: { title: "مكتبة نيكسس", available: "حركة متاحة", search_ph: "بحث...", filters: { all: "الكل", chest: "صدر", back: "ظهر", legs: "أرجل", shoulders: "أكتاف", arms: "أذرع", abs: "بطن", cardio: "كارديو" }, protocol: "البروتوكول:", btn_video: "فيديو", btn_add: "إضافة", empty_search: "لا نتائج لـ" },
      history: { title: "سجل التمارين", stats_total: "مجموع الجلسات", stats_valid: "تمارين مكتملة", timeline: "الجدول الزمني", session_active: "جلسة نشطة", session_rest: "راحة", completed_ex: "تمارين", empty: "لا سجل." },
      nutrition: { title: "الوقود", subtitle: "التغذية", consumed: "تم استهلاكه", target: "الهدف", ia_title: "خبير التغذية", ia_desc: "أنشئ خطة وجبات أسبوعية كاملة.", pref_label: "تفضيلات", pref_ph: "مثال: نباتي، ميزانية منخفضة...", btn_generate: "توليد الخطة", btn_regen: "إعادة التوليد", alert_title: "القائمة جاهزة", alert_msg: "تم إنشاء خطتك.", alert_error: "فشل التوليد.", alert_zone: "منطقة خاطئة", alert_zone_msg: "ركز على خطة اليوم." },
      systems: { title: "الأنظمة", subtitle: "مركز القيادة", search_ph: "بحث عن بروتوكول...", locked_alert: "وحدة مميزة", locked_msg: "رقي للعضوية لفتح الوحدة", btn_unlock: "فتح", soon_title: "قريباً", soon_msg: "قيد التطوير.", categories: { bio: "التتبع الحيوي", perf: "الأداء", nutri: "التغذية", recup: "الاستشفاء" }, modules: { body_fat: "نسبة الدهون", water: "الترطيب", tdee: "الأيض", bmi: "مؤشر الكتلة", sleep: "النوم", stress: "الإجهاد", heart: "القلب", body: "طاقة الجسم", '1rm': "حاسبة 1RM", timer: "المؤقت", workout_log: "سجل التمارين", reflex: "رد الفعل", vision: "الرؤية", posture: "الوضعية", macros: "الماكروز", shopping: "التسوق", supps: "المكملات", fasting: "الصيام", meal_prep: "تحضير الوجبات", breath: "التنفس", stretching: "الإطالة", mood: "المزاج", meditation: "التأمل", journaling: "الدوين", cold: "التعرض للبرد", nootropics: "المنشطات الذهنية", env: "البيئة", hrv: "تقلب القلب", discharge: "تفريغ عصبي" } },
      subscription: { badge: "نيكسس إيليت", status_badge: "الحالة: عضو نخبة", title_free: "تجاوز الحدود", title_pro: "اشتراكك", subtitle: "افتح ذكاءً اصطناعياً كاملاً لتحول جسدي متسارع.", active_title: "اشتراك نشط", active_renewal: "التجديد القادم: 01/01/2026", manage_btn: "إدارة / إلغاء", manage_info: "سيتم تحويلك لإعدادات المتجر.", features: { coach: "مدرب ذكي غير محدود", plans: "خطط مخصصة 100%", bio: "تحليل حيوي", recipes: "وصفات وقوائم", support: "دعم ذو أولوية" }, price_month: "/ شهر", btn_start: "ابدأ التجربة", btn_restore: "استعادة المشتريات", legal_terms: "الشروط", legal_privacy: "الخصوصية", alert_pay_title: "دفع (محاكاة)", alert_pay_msg: "في الإنتاج عبر RevenueCat.", alert_restore: "استعادة", alert_restore_msg: "جاري البحث..." },
      workout_tracker: { title: "متتبع التمارين", available_moves: "حركات متاحة", ia_title: "مولد البرامج", ia_desc: "الذكاء الاصطناعي سينشئ خطة أسبوعية.", label_focus: "تركيز خاص", ph_focus: "صدر، أرداف...", btn_generate: "توليد البرنامج", plan_active: "خطة نشطة", btn_finish: "إنهاء", btn_regen: "توليد جديد", alert_ready_title: "جاهز", alert_ready_msg: "أسبوعك جاهز!", alert_empty_title: "فارغ", alert_empty_msg: "اختر تمرينًا.", alert_saved_title: "تم الحفظ!", alert_saved_msg: "تم التحديث.", btn_history: "السجل", week_sessions: "جلسات/أسبوع", day_session: "جلسة", exos_count: "تمارين", btn_demo: "فيديو", protocol: "البروتوكول:" },
      shopping: { title: "التسوق", add_ph: "أضف...", empty: "فارغة.", empty_sub: "أضف عناصر." },
      timer: { title: "المؤقت", mode_rest: "راحة", mode_tabata: "تاباتا", start: "ابدأ", stop: "توقف", reset: "إعادة", rounds: "جولات", work: "عمل", rest: "راحة" }
    }
  }
};

const deviceLanguage = Localization.getLocales()[0]?.languageCode ?? 'fr';

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: deviceLanguage, 
    fallbackLng: 'en',
    interpolation: { escapeValue: false },
  });

export default i18n;