// Base de données massive d'exercices (Version Étendue)
// Cette structure permet de filtrer facilement par muscle, équipement ou difficulté.

export const EXERCISES_DB = [
  // ===========================================================================
  // PECTORAUX (CHEST)
  // ===========================================================================
  { id: 'pec_1', name: 'Développé Couché Barre', muscle: 'Pectoraux', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Allongé sur le banc, pieds au sol. Descendez la barre au niveau des tétons, poussez explosif." },
  { id: 'pec_2', name: 'Développé Incliné Barre', muscle: 'Pectoraux', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Banc à 30-45°. Cible le haut des pectoraux. Descendez la barre sur le haut du sternum." },
  { id: 'pec_3', name: 'Développé Couché Haltères', muscle: 'Pectoraux', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Permet une meilleure amplitude. Gardez les coudes à 45° du corps." },
  { id: 'pec_4', name: 'Développé Incliné Haltères', muscle: 'Pectoraux', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Contrôlez bien la descente pour étirer le haut des pecs." },
  { id: 'pec_5', name: 'Écarté Couché', muscle: 'Pectoraux', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Bras légèrement fléchis. Imaginez que vous faites un câlin à un gros arbre." },
  { id: 'pec_6', name: 'Écarté Incliné', muscle: 'Pectoraux', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Variante inclinée pour le haut des pectoraux." },
  { id: 'pec_7', name: 'Dips (Barres Parallèles)', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Penchez le buste en avant pour cibler les pecs. Descendez jusqu'à 90°." },
  { id: 'pec_8', name: 'Pompes Classiques', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Corps gainé, descendez la poitrine au sol." },
  { id: 'pec_9', name: 'Pompes Pieds Surélevés', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Cible le haut des pectoraux. Pieds sur un banc ou une chaise." },
  { id: 'pec_10', name: 'Crossover Poulie Haute', muscle: 'Pectoraux', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Tirez les poignées vers le bas devant le bassin. Contractez fort." },
  { id: 'pec_11', name: 'Crossover Poulie Basse', muscle: 'Pectoraux', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Tirez vers le haut pour cibler le haut des pecs." },
  { id: 'pec_12', name: 'Développé Machine Assis', muscle: 'Pectoraux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Mouvement guidé sécurisé pour l'hypertrophie." },
  { id: 'pec_13', name: 'Pec Deck (Papillon)', muscle: 'Pectoraux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Isolation pure. Gardez les coudes hauts." },
  { id: 'pec_14', name: 'Pull-over Haltère', muscle: 'Pectoraux', equipment: 'Haltère', difficulty: 'Intermédiaire', instructions: "Étire la cage thoracique et les dorsaux/pecs." },
  { id: 'pec_15', name: 'Développé Guillotine', muscle: 'Pectoraux', equipment: 'Barre', difficulty: 'Avancé', instructions: "Barre descendue vers le cou. Attention aux épaules." },
  { id: 'pec_16', name: 'Pompes Diamant', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Mains jointes sous la poitrine. Cible l'intérieur et les triceps." },
  { id: 'pec_17', name: 'Développé Décliné', muscle: 'Pectoraux', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Cible le bas des pectoraux." },
  { id: 'pec_18', name: 'Presse Pectorale Convergente', muscle: 'Pectoraux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Mouvement naturel de convergence." },
  { id: 'pec_19', name: 'Svend Press', muscle: 'Pectoraux', equipment: 'Disque', difficulty: 'Débutant', instructions: "Pressez deux disques l'un contre l'autre devant vous." },
  { id: 'pec_20', name: 'Pompes Claquées', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Explosivité maximale." },
  { id: 'pec_21', name: 'Développé Couché Sol (Floor Press)', muscle: 'Pectoraux', equipment: 'Barre/Haltères', difficulty: 'Intermédiaire', instructions: "Allongé au sol. Limite l'amplitude pour protéger les épaules." },
  { id: 'pec_22', name: 'Pompes Lestées', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Pompes avec un disque sur le dos ou un gilet lesté." },
  { id: 'pec_23', name: 'Écarté Poulie Vis-à-vis', muscle: 'Pectoraux', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Debout, amenez les poignées devant la poitrine." },
  { id: 'pec_24', name: 'Développé Incliné Machine', muscle: 'Pectoraux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Isolation sécurisée du haut des pectoraux." },
  { id: 'pec_25', name: 'Pompes Archer', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Descendez d'un côté en tendant l'autre bras." },
  { id: 'pec_26', name: 'Développé Couché Prise Inversée', muscle: 'Pectoraux', equipment: 'Barre', difficulty: 'Avancé', instructions: "Cible le haut des pectoraux. Attention à la prise." },
  { id: 'pec_27', name: 'Pompes Spiderman', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Ramenez un genou au coude en descendant." },
  { id: 'pec_28', name: 'Hex Press', muscle: 'Pectoraux', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Haltères collés l'un contre l'autre tout le long du mouvement." },
  { id: 'pec_29', name: 'Développé Unilatéral Machine', muscle: 'Pectoraux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Un bras à la fois pour corriger les déséquilibres." },
  { id: 'pec_30', name: 'Burpees avec Pompe', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Cardio et force." },
  { id: 'pec_31', name: 'TRX Chest Press', muscle: 'Pectoraux', equipment: 'TRX', difficulty: 'Intermédiaire', instructions: "Pompes suspendues instables." },
  { id: 'pec_32', name: 'TRX Chest Fly', muscle: 'Pectoraux', equipment: 'TRX', difficulty: 'Avancé', instructions: "Écartés suspendus. Très difficile pour les stabilisateurs." },
  { id: 'pec_33', name: 'Développé Smith Machine', muscle: 'Pectoraux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Barre guidée. Idéal pour aller à l'échec." },
  { id: 'pec_34', name: 'Landmine Chest Press', muscle: 'Pectoraux', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Poussée à genoux ou debout avec la barre ancrée." },
  { id: 'pec_35', name: 'Pompes Hindu', muscle: 'Pectoraux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Mouvement de vague pour la souplesse et la force." },

  // ===========================================================================
  // DOS (BACK)
  // ===========================================================================
  { id: 'dos_1', name: 'Tractions Pronation (Pull-ups)', muscle: 'Dos', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Mains plus larges que les épaules. Cible le grand dorsal." },
  { id: 'dos_2', name: 'Tractions Supination (Chin-ups)', muscle: 'Dos', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Paumes vers soi. Sollicite davantage les biceps." },
  { id: 'dos_3', name: 'Tirage Vertical Poitrine', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Alternative aux tractions. Gardez le dos droit." },
  { id: 'dos_4', name: 'Tirage Nuque', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Attention à la coiffe des rotateurs. Charge légère." },
  { id: 'dos_5', name: 'Tirage Horizontal (Rowing)', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Ramenez la poignée au nombril. Resserrer les omoplates." },
  { id: 'dos_6', name: 'Rowing Barre (Yates)', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Buste à 45°. Prise supination pour le bas des dorsaux." },
  { id: 'dos_7', name: 'Rowing Barre (Pendlay)', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Buste parallèle au sol. Reposez la barre à chaque rep." },
  { id: 'dos_8', name: 'Rowing Haltère Unilatéral', muscle: 'Dos', equipment: 'Haltère', difficulty: 'Intermédiaire', instructions: "Un genou sur le banc. Tirez le coude vers le plafond." },
  { id: 'dos_9', name: 'Rowing T-Bar', muscle: 'Dos', equipment: 'Machine', difficulty: 'Intermédiaire', instructions: "Prise neutre ou large. Grosse charge possible." },
  { id: 'dos_10', name: 'Soulevé de Terre (Deadlift)', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Roi des exercices. Dos plat impératif. Poussez avec les jambes." },
  { id: 'dos_11', name: 'Rack Pull', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Demi soulevé de terre. Cible l'épaisseur du dos." },
  { id: 'dos_12', name: 'Pull-over Poulie Haute', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Bras tendus. Isolation du grand dorsal." },
  { id: 'dos_13', name: 'Shrugs Barre', muscle: 'Dos', equipment: 'Barre', difficulty: 'Débutant', instructions: "Haussement d'épaules pour les trapèzes." },
  { id: 'dos_14', name: 'Shrugs Haltères', muscle: 'Dos', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Variante aux haltères." },
  { id: 'dos_15', name: 'Extensions Lombaires', muscle: 'Dos', equipment: 'Banc', difficulty: 'Débutant', instructions: "Renforce le bas du dos. Ne pas hyper-extenser." },
  { id: 'dos_16', name: 'Good Morning', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Chaîne postérieure. Gardez les jambes semi-tendues." },
  { id: 'dos_17', name: 'Tirage Vertical Prise Serrée', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Prise neutre triangle." },
  { id: 'dos_18', name: 'Rowing Meadows', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Rowing unilatéral avec barre T." },
  { id: 'dos_19', name: 'Seal Row', muscle: 'Dos', equipment: 'Barre/Haltères', difficulty: 'Intermédiaire', instructions: "Allongé ventre sur un banc surélevé. Isolation totale." },
  { id: 'dos_20', name: 'Face Pull', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Pour la santé des épaules et les deltoïdes postérieurs." },
  { id: 'dos_21', name: 'Tractions Australiennes', muscle: 'Dos', equipment: 'Barre basse', difficulty: 'Débutant', instructions: "Corps sous une barre basse, tirez la poitrine vers la barre." },
  { id: 'dos_22', name: 'Rowing Machine Assis', muscle: 'Dos', equipment: 'Machine', difficulty: 'Débutant', instructions: "Machine guidée pour le dos." },
  { id: 'dos_23', name: 'Tirage Vertical Machine', muscle: 'Dos', equipment: 'Machine', difficulty: 'Débutant', instructions: "Variante guidée du tirage poulie." },
  { id: 'dos_24', name: 'Renegade Row', muscle: 'Dos', equipment: 'Haltères', difficulty: 'Avancé', instructions: "En position pompe, tirez un haltère vers la hanche." },
  { id: 'dos_25', name: 'Kroc Row', muscle: 'Dos', equipment: 'Haltère', difficulty: 'Avancé', instructions: "Rowing haltère lourd, reps élevées, léger élan toléré." },
  { id: 'dos_26', name: 'Straight Arm Pushdown', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Bras tendus, poussez la barre vers les cuisses." },
  { id: 'dos_27', name: 'Shrugs Smith Machine', muscle: 'Dos', equipment: 'Machine', difficulty: 'Débutant', instructions: "Shrugs guidés." },
  { id: 'dos_28', name: 'Superman', muscle: 'Dos', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Allongé au sol, levez bras et jambes simultanément." },
  { id: 'dos_29', name: 'TRX Row', muscle: 'Dos', equipment: 'TRX', difficulty: 'Débutant', instructions: "Tirage au poids du corps incliné." },
  { id: 'dos_30', name: 'Bird Dog', muscle: 'Dos', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "À quatre pattes, tendez bras et jambe opposés." },
  { id: 'dos_31', name: 'Reeves Deadlift', muscle: 'Dos', equipment: 'Barre', difficulty: 'Avancé', instructions: "Soulevé de terre en tenant les disques (pincement)." },
  { id: 'dos_32', name: 'Jefferson Curl', muscle: 'Dos', equipment: 'Barre', difficulty: 'Expert', instructions: "Flexion vertébrale contrôlée. Charge très légère." },
  { id: 'dos_33', name: 'Lat Prayer', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Variante du pull-over à genoux face à la poulie." },
  { id: 'dos_34', name: 'Chest Supported Row', muscle: 'Dos', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Rowing ventre sur banc incliné." },
  { id: 'dos_35', name: 'Single Arm Lat Pulldown', muscle: 'Dos', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Tirage vertical unilatéral pour la symétrie." },

  // ===========================================================================
  // JAMBES (LEGS)
  // ===========================================================================
  { id: 'leg_1', name: 'Squat Arrière (Back Squat)', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Avancé', instructions: "Barre sur les trapèzes. Descendez fesses en arrière." },
  { id: 'leg_2', name: 'Squat Avant (Front Squat)', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Avancé', instructions: "Barre sur les clavicules. Cible davantage les quadriceps." },
  { id: 'leg_3', name: 'Presse à Cuisses', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Pieds largeur épaules. Ne verrouillez pas les genoux." },
  { id: 'leg_4', name: 'Fentes Avant', muscle: 'Jambes', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Dos droit. Le genou arrière frôle le sol." },
  { id: 'leg_5', name: 'Fentes Arrière', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Moins de stress sur les genoux que les fentes avant." },
  { id: 'leg_6', name: 'Fentes Bulgares', muscle: 'Jambes', equipment: 'Haltères', difficulty: 'Avancé', instructions: "Pied arrière sur un banc. Brûlure garantie." },
  { id: 'leg_7', name: 'Leg Extension', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Isolation quadriceps. Contrôlez la descente." },
  { id: 'leg_8', name: 'Leg Curl Allongé', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Isolation ischios-jambiers." },
  { id: 'leg_9', name: 'Leg Curl Assis', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Souvent plus efficace pour les ischios." },
  { id: 'leg_10', name: 'Soulevé de Terre Jambes Tendues', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Cible les ischios et fessiers. Dos plat !" },
  { id: 'leg_11', name: 'Hip Thrust', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Le roi pour les fessiers. Barre sur le bassin." },
  { id: 'leg_12', name: 'Extension Mollets Debout', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Amplitude complète pour les mollets." },
  { id: 'leg_13', name: 'Extension Mollets Assis', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Cible le soléaire (muscle profond)." },
  { id: 'leg_14', name: 'Hack Squat', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Intermédiaire', instructions: "Squat guidé, excellent pour les quadris." },
  { id: 'leg_15', name: 'Goblet Squat', muscle: 'Jambes', equipment: 'Kettlebell', difficulty: 'Débutant', instructions: "Poids tenu contre la poitrine. Idéal pour apprendre." },
  { id: 'leg_16', name: 'Sissy Squat', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Isolation extrême des quadriceps." },
  { id: 'leg_17', name: 'Abducteurs Machine', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Cible le moyen fessier." },
  { id: 'leg_18', name: 'Adducteurs Machine', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Cible l'intérieur des cuisses." },
  { id: 'leg_19', name: 'Step-ups', muscle: 'Jambes', equipment: 'Banc', difficulty: 'Intermédiaire', instructions: "Montez sur le banc en poussant sur une jambe." },
  { id: 'leg_20', name: 'Pistol Squat', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Expert', instructions: "Squat sur une seule jambe. Équilibre requis." },
  { id: 'leg_21', name: 'Squat Sumo', muscle: 'Jambes', equipment: 'Barre/Haltère', difficulty: 'Intermédiaire', instructions: "Pieds très écartés. Cible adducteurs et fessiers." },
  { id: 'leg_22', name: 'Zercher Squat', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Avancé', instructions: "Barre tenue dans le pli des coudes." },
  { id: 'leg_23', name: 'Box Squat', muscle: 'Jambes', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Asseyez-vous sur une boîte avant de remonter." },
  { id: 'leg_24', name: 'Jump Squat', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Squat explosif avec saut." },
  { id: 'leg_25', name: 'Wall Sit (Chaise)', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Dos au mur, cuisses parallèles au sol. Tenez." },
  { id: 'leg_26', name: 'Glute Bridge', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Pont fessier au sol." },
  { id: 'leg_27', name: 'Donkey Kicks', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "À quatre pattes, levez la jambe vers le ciel." },
  { id: 'leg_28', name: 'Nordic Hamstring Curl', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Expert', instructions: "Pieds bloqués, descendez le buste vers le sol." },
  { id: 'leg_29', name: 'Belt Squat', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Intermédiaire', instructions: "Squat avec poids à la ceinture (préserve le dos)." },
  { id: 'leg_30', name: 'Mollets Presse à Cuisses', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Extension des chevilles sur la presse." },
  { id: 'leg_31', name: 'Fentes Sautées', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Alternance explosive des jambes." },
  { id: 'leg_32', name: 'Cossack Squat', muscle: 'Jambes', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Fente latérale profonde." },
  { id: 'leg_33', name: 'Reverse Hyperextension', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Intermédiaire', instructions: "Renforce fessiers et lombaires sans compression." },
  { id: 'leg_34', name: 'Cable Pull Through', muscle: 'Jambes', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Dos à la poulie, extension de hanches." },
  { id: 'leg_35', name: 'Smith Machine Squat', muscle: 'Jambes', equipment: 'Machine', difficulty: 'Débutant', instructions: "Squat guidé." },

  // ===========================================================================
  // ÉPAULES (SHOULDERS)
  // ===========================================================================
  { id: 'should_1', name: 'Développé Militaire Debout', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Avancé', instructions: "Dos droit, abdos gainés. Poussez la barre au-dessus de la tête." },
  { id: 'should_2', name: 'Développé Haltères Assis', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Dossier à 90°. Protège les lombaires." },
  { id: 'should_3', name: 'Élévations Latérales', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Cible le faisceau latéral. Ne montez pas plus haut que les épaules." },
  { id: 'should_4', name: 'Élévations Frontales', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Cible l'avant de l'épaule." },
  { id: 'should_5', name: 'Oiseau (Rear Delt Fly)', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Buste penché. Cible l'arrière de l'épaule." },
  { id: 'should_6', name: 'Tirage Menton (Upright Row)', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Prise large pour préserver les poignets." },
  { id: 'should_7', name: 'Face Pull', muscle: 'Épaules', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Indispensable pour la posture." },
  { id: 'should_8', name: 'Développé Arnold', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Rotation des poignets pendant la montée." },
  { id: 'should_9', name: 'Élévations Latérales Poulie', muscle: 'Épaules', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Tension continue sur le muscle." },
  { id: 'should_10', name: 'Shrugs', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Débutant', instructions: "Pour les trapèzes supérieurs." },
  { id: 'should_11', name: 'Développé Nuque', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Avancé', instructions: "À éviter si manque de souplesse." },
  { id: 'should_12', name: 'Landmine Press', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Poussée unilatérale avec barre ancrée au sol." },
  { id: 'should_13', name: 'Lu Raises', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Avancé', instructions: "Élévation latérale complète jusqu'au dessus de la tête." },
  { id: 'should_14', name: 'Y-Raise', muscle: 'Épaules', equipment: 'Banc', difficulty: 'Intermédiaire', instructions: "Allongé ventre sur banc incliné, levez les bras en Y." },
  { id: 'should_15', name: 'Pec Deck Inversé', muscle: 'Épaules', equipment: 'Machine', difficulty: 'Débutant', instructions: "Pour l'arrière d'épaule." },
  { id: 'should_16', name: 'Push Press', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Avancé', instructions: "Développé militaire avec impulsion des jambes." },
  { id: 'should_17', name: 'Élévations Frontales Disque', muscle: 'Épaules', equipment: 'Disque', difficulty: 'Débutant', instructions: "Tenez un disque à deux mains devant vous." },
  { id: 'should_18', name: 'Élévations Latérales Assis', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Élimine l'élan du corps." },
  { id: 'should_19', name: 'Face Pull à Genoux', muscle: 'Épaules', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Plus de gainage requis." },
  { id: 'should_20', name: 'Développé Machine Épaules', muscle: 'Épaules', equipment: 'Machine', difficulty: 'Débutant', instructions: "Mouvement guidé." },
  { id: 'should_21', name: 'Cuban Press', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Avancé', instructions: "Tirage menton + Rotation externe + Développé." },
  { id: 'should_22', name: 'Bradford Press', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Avancé', instructions: "Passez la barre devant puis derrière la tête sans verrouiller." },
  { id: 'should_23', name: 'Élévations Frontales Poulie', muscle: 'Épaules', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Poulie basse, entre les jambes." },
  { id: 'should_24', name: 'Oiseau Poulie Vis-à-vis', muscle: 'Épaules', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Croisez les câbles pour l'arrière d'épaule." },
  { id: 'should_25', name: 'Handstand Push-up', muscle: 'Épaules', equipment: 'Poids du corps', difficulty: 'Expert', instructions: "Pompes en poirier contre un mur." },
  { id: 'should_26', name: 'Pike Push-up', muscle: 'Épaules', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Corps en V inversé, cible les épaules." },
  { id: 'should_27', name: 'Around the World', muscle: 'Épaules', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Rotation complète des bras autour de la tête." },
  { id: 'should_28', name: 'Clean and Press', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Expert', instructions: "Épaulé-jeté. Mouvement olympique." },
  { id: 'should_29', name: 'Kettlebell Halo', muscle: 'Épaules', equipment: 'Kettlebell', difficulty: 'Débutant', instructions: "Tournez le KB autour de la tête." },
  { id: 'should_30', name: 'Scapular Pull-up', muscle: 'Épaules', equipment: 'Barre', difficulty: 'Débutant', instructions: "Juste le mouvement des omoplates suspendu." },

  // ===========================================================================
  // BRAS (BICEPS / TRICEPS / AVANT-BRAS)
  // ===========================================================================
  { id: 'arms_1', name: 'Curl Barre Debout', muscle: 'Bras', equipment: 'Barre', difficulty: 'Débutant', instructions: "Le classique pour la masse des biceps." },
  { id: 'arms_2', name: 'Curl Haltères', muscle: 'Bras', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Rotation du poignet en montant (supination)." },
  { id: 'arms_3', name: 'Curl Marteau', muscle: 'Bras', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Prise neutre. Cible le brachial et l'avant-bras." },
  { id: 'arms_4', name: 'Curl Pupitre (Larry Scott)', muscle: 'Bras', equipment: 'Machine/Barre', difficulty: 'Intermédiaire', instructions: "Isolation stricte, impossible de tricher." },
  { id: 'arms_5', name: 'Curl Incliné', muscle: 'Bras', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Étire le biceps à l'origine." },
  { id: 'arms_6', name: 'Curl Araignée (Spider)', muscle: 'Bras', equipment: 'Banc', difficulty: 'Intermédiaire', instructions: "Ventre sur banc incliné." },
  { id: 'arms_7', name: 'Barre au Front', muscle: 'Bras', equipment: 'Barre EZ', difficulty: 'Intermédiaire', instructions: "Masse des triceps." },
  { id: 'arms_8', name: 'Extensions Poulie Haute', muscle: 'Bras', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Coudes collés au corps." },
  { id: 'arms_9', name: 'Kickback Haltère', muscle: 'Bras', equipment: 'Haltère', difficulty: 'Débutant', instructions: "Finition triceps." },
  { id: 'arms_10', name: 'Dips Banc', muscle: 'Bras', equipment: 'Banc', difficulty: 'Débutant', instructions: "Poids du corps pour triceps." },
  { id: 'arms_11', name: 'Développé Couché Prise Serrée', muscle: 'Bras', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Grosse charge pour les triceps." },
  { id: 'arms_12', name: 'Extension Nuque', muscle: 'Bras', equipment: 'Haltère', difficulty: 'Intermédiaire', instructions: "Étire la longue portion du triceps." },
  { id: 'arms_13', name: 'Curl Câble', muscle: 'Bras', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Tension constante." },
  { id: 'arms_14', name: 'Curl Concentration', muscle: 'Bras', equipment: 'Haltère', difficulty: 'Débutant', instructions: "Coude calé contre la cuisse." },
  { id: 'arms_15', name: 'Zottman Curl', muscle: 'Bras', equipment: 'Haltères', difficulty: 'Intermédiaire', instructions: "Montez en supination, descendez en pronation." },
  { id: 'arms_16', name: 'Drag Curl', muscle: 'Bras', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "Tirez la barre le long du corps, coudes en arrière." },
  { id: 'arms_17', name: 'Curl Inversé', muscle: 'Bras', equipment: 'Barre', difficulty: 'Débutant', instructions: "Prise pronation pour les avant-bras." },
  { id: 'arms_18', name: '21s', muscle: 'Bras', equipment: 'Barre', difficulty: 'Intermédiaire', instructions: "7 demies reps bas, 7 demies reps haut, 7 complètes." },
  { id: 'arms_19', name: 'Tate Press', muscle: 'Bras', equipment: 'Haltères', difficulty: 'Avancé', instructions: "Extensions triceps coudes écartés." },
  { id: 'arms_20', name: 'JM Press', muscle: 'Bras', equipment: 'Barre', difficulty: 'Avancé', instructions: "Hybride entre développé serré et barre au front." },
  { id: 'arms_21', name: 'Extensions Triceps Corde', muscle: 'Bras', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Écartez la corde en bas du mouvement." },
  { id: 'arms_22', name: 'Extensions Unilatérales Poulie', muscle: 'Bras', equipment: 'Poulie', difficulty: 'Débutant', instructions: "Prise inversée possible." },
  { id: 'arms_23', name: 'Dips Machine', muscle: 'Bras', equipment: 'Machine', difficulty: 'Débutant', instructions: "Dips assistés ou machine triceps." },
  { id: 'arms_24', name: 'Curl Poulie Vis-à-vis (High Cable Curl)', muscle: 'Bras', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Position de double biceps." },
  { id: 'arms_25', name: 'Waiters Curl', muscle: 'Bras', equipment: 'Haltère', difficulty: 'Débutant', instructions: "Tenez le disque de l'haltère à deux mains." },
  { id: 'arms_26', name: 'Wrist Curl (Flexion poignet)', muscle: 'Bras', equipment: 'Barre', difficulty: 'Débutant', instructions: "Pour l'intérieur des avant-bras." },
  { id: 'arms_27', name: 'Reverse Wrist Curl (Extension)', muscle: 'Bras', equipment: 'Barre', difficulty: 'Débutant', instructions: "Pour l'extérieur des avant-bras." },
  { id: 'arms_28', name: 'Farmer Walk', muscle: 'Bras', equipment: 'Haltères', difficulty: 'Débutant', instructions: "Marchez avec des haltères lourds. Grip." },
  { id: 'arms_29', name: 'Plate Pinch', muscle: 'Bras', equipment: 'Disques', difficulty: 'Débutant', instructions: "Tenez deux disques pincés ensemble." },
  { id: 'arms_30', name: 'Suspension (Dead Hang)', muscle: 'Bras', equipment: 'Barre', difficulty: 'Débutant', instructions: "Restez suspendu le plus longtemps possible." },

  // ===========================================================================
  // ABDOMINAUX (ABS)
  // ===========================================================================
  { id: 'abs_1', name: 'Crunch Sol', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Décollez les épaules, pas le bas du dos." },
  { id: 'abs_2', name: 'Relevé de Jambes Suspendu', muscle: 'Abdominaux', equipment: 'Barre', difficulty: 'Avancé', instructions: "Sans élan. Cible le bas des abdos." },
  { id: 'abs_3', name: 'Planche (Gainage)', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Corps droit comme une planche." },
  { id: 'abs_4', name: 'Crunch Câble', muscle: 'Abdominaux', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "À genoux, enroulez le buste." },
  { id: 'abs_5', name: 'Roulette à Abdos (Ab Wheel)', muscle: 'Abdominaux', equipment: 'Roue', difficulty: 'Avancé', instructions: "Ne cambrez pas le dos !" },
  { id: 'abs_6', name: 'Russian Twist', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Rotation du buste pour les obliques." },
  { id: 'abs_7', name: 'Mountain Climbers', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Cardio et gainage dynamique." },
  { id: 'abs_8', name: 'Vacuum', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Rentrez le ventre au maximum. Pour le transverse." },
  { id: 'abs_9', name: 'Relevé de Genoux (Chaise Romaine)', muscle: 'Abdominaux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Dos collé au dossier." },
  { id: 'abs_10', name: 'Woodchopper', muscle: 'Abdominaux', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Mouvement de bûcheron en rotation." },
  { id: 'abs_11', name: 'Planche Latérale', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Gainage des obliques." },
  { id: 'abs_12', name: 'V-Ups', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Touchez vos pieds avec vos mains en V." },
  { id: 'abs_13', name: 'Bicyclette', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Coude gauche vers genou droit, et inversement." },
  { id: 'abs_14', name: 'Dragon Flag', muscle: 'Abdominaux', equipment: 'Banc', difficulty: 'Expert', instructions: "Exercice de Bruce Lee. Corps droit, pivot sur les épaules." },
  { id: 'abs_15', name: 'Toes to Bar', muscle: 'Abdominaux', equipment: 'Barre', difficulty: 'Avancé', instructions: "Amenez les orteils à la barre." },
  { id: 'abs_16', name: 'Sit-ups', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Relevé de buste complet." },
  { id: 'abs_17', name: 'Hollow Body Hold', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Corps en banane, lombaires collées au sol." },
  { id: 'abs_18', name: 'Pallof Press', muscle: 'Abdominaux', equipment: 'Poulie', difficulty: 'Intermédiaire', instructions: "Anti-rotation. Résistez à la force qui vous tourne." },
  { id: 'abs_19', name: 'Relevé de Bassin (Reverse Crunch)', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Décollez le bassin vers le ciel." },
  { id: 'abs_20', name: 'L-Sit', muscle: 'Abdominaux', equipment: 'Barres', difficulty: 'Avancé', instructions: "Tenez les jambes à l'équerre." },
  { id: 'abs_21', name: 'Flutter Kicks', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Battements de jambes au ras du sol." },
  { id: 'abs_22', name: 'Crunch Machine', muscle: 'Abdominaux', equipment: 'Machine', difficulty: 'Débutant', instructions: "Abdos guidés avec poids." },
  { id: 'abs_23', name: 'Oblique Crunch', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Crunch sur le côté." },
  { id: 'abs_24', name: 'Windshield Wipers', muscle: 'Abdominaux', equipment: 'Barre', difficulty: 'Expert', instructions: "Essuie-glace suspendu." },
  { id: 'abs_25', name: 'Dead Bug', muscle: 'Abdominaux', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Coordination et gainage profond." },

  // ===========================================================================
  // CARDIO / CROSSFIT
  // ===========================================================================
  { id: 'cardio_1', name: 'Burpees', muscle: 'Cardio', equipment: 'Poids du corps', difficulty: 'Avancé', instructions: "Pompe + Saut." },
  { id: 'cardio_2', name: 'Corde à sauter', muscle: 'Cardio', equipment: 'Corde', difficulty: 'Intermédiaire', instructions: "Jeu de jambes." },
  { id: 'cardio_3', name: 'Kettlebell Swing', muscle: 'Cardio', equipment: 'Kettlebell', difficulty: 'Intermédiaire', instructions: "Extension de hanches explosive." },
  { id: 'cardio_4', name: 'Rameur', muscle: 'Cardio', equipment: 'Machine', difficulty: 'Débutant', instructions: "Dos droit, poussez avec les jambes." },
  { id: 'cardio_5', name: 'Assault Bike', muscle: 'Cardio', equipment: 'Machine', difficulty: 'Avancé', instructions: "L'enfer sur roues." },
  { id: 'cardio_6', name: 'Box Jump', muscle: 'Cardio', equipment: 'Box', difficulty: 'Intermédiaire', instructions: "Saut à pieds joints sur la boîte." },
  { id: 'cardio_7', name: 'Jumping Jacks', muscle: 'Cardio', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Saut écart." },
  { id: 'cardio_8', name: 'High Knees (Montées de genoux)', muscle: 'Cardio', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Genoux à la poitrine, rythme rapide." },
  { id: 'cardio_9', name: 'Battle Ropes', muscle: 'Cardio', equipment: 'Corde', difficulty: 'Intermédiaire', instructions: "Vagues avec cordes lourdes." },
  { id: 'cardio_10', name: 'Sled Push (Prowler)', muscle: 'Cardio', equipment: 'Chariot', difficulty: 'Avancé', instructions: "Poussez le chariot lourd." },
  { id: 'cardio_11', name: 'Sled Pull', muscle: 'Cardio', equipment: 'Chariot', difficulty: 'Intermédiaire', instructions: "Tirez le chariot en reculant." },
  { id: 'cardio_12', name: 'Wall Ball', muscle: 'Cardio', equipment: 'Ballon', difficulty: 'Intermédiaire', instructions: "Squat + lancer de ballon sur cible." },
  { id: 'cardio_13', name: 'Double Unders', muscle: 'Cardio', equipment: 'Corde', difficulty: 'Avancé', instructions: "Deux tours de corde par saut." },
  { id: 'cardio_14', name: 'SkiErg', muscle: 'Cardio', equipment: 'Machine', difficulty: 'Intermédiaire', instructions: "Simulation de ski de fond." },
  { id: 'cardio_15', name: 'Thrusters', muscle: 'Cardio', equipment: 'Barre', difficulty: 'Avancé', instructions: "Squat avant + Développé militaire." },
  { id: 'cardio_16', name: 'Muscle-up', muscle: 'Cardio', equipment: 'Barre/Anneaux', difficulty: 'Expert', instructions: "Traction explosive + Dips." },
  { id: 'cardio_17', name: 'Handstand Walk', muscle: 'Cardio', equipment: 'Poids du corps', difficulty: 'Expert', instructions: "Marche sur les mains." },
  { id: 'cardio_18', name: 'Tire Flip', muscle: 'Cardio', equipment: 'Pneu', difficulty: 'Avancé', instructions: "Retourner un pneu de tracteur." },
  { id: 'cardio_19', name: 'Sandbag Carry', muscle: 'Cardio', equipment: 'Sac', difficulty: 'Intermédiaire', instructions: "Porter un sac de sable lourd." },
  { id: 'cardio_20', name: 'Bear Crawl', muscle: 'Cardio', equipment: 'Poids du corps', difficulty: 'Débutant', instructions: "Marche de l'ours." },
  { id: 'cardio_21', name: 'Stairmaster (Escaliers)', muscle: 'Cardio', equipment: 'Machine', difficulty: 'Débutant', instructions: "Montez les marches sans fin." },
  { id: 'cardio_22', name: 'Course à pied (Tapis)', muscle: 'Cardio', equipment: 'Machine', difficulty: 'Débutant', instructions: "Running classique." },
  { id: 'cardio_23', name: 'Elliptique', muscle: 'Cardio', equipment: 'Machine', difficulty: 'Débutant', instructions: "Cardio sans impact." },
  { id: 'cardio_24', name: 'Shadow Boxing', muscle: 'Cardio', equipment: 'Poids du corps', difficulty: 'Intermédiaire', instructions: "Boxe dans le vide." },
  { id: 'cardio_25', name: 'Turkish Get Up', muscle: 'Cardio', equipment: 'Kettlebell', difficulty: 'Avancé', instructions: "Se relever du sol avec un poids au dessus de la tête." },
];